server:
  port: 8085
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true  

spring:
  application:
    name: store-demo-gateway
  cloud:
    gateway:
      routes:
      - id: rvyModule
        uri: lb://STORE-DEMO-SERVICE
        predicates:
        - Path=/rvy/v1/**